sudo: required
services:
  - docker

before_install:
  - docker build -t chanai0125/docker-ci-cd -f Dockerfile.dev .

script:
  - docker run -e CI=true chanai0125/docker-ci-cd npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-ci-cd"
  env: "Dockercicd-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-770492388321"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY